name: TwitchLink
author: Azrotho
api-version: 1.20
version: 1.0
main: fr.azrotho.twitchlink.TwitchLink
commands:
  debug:
    description: Debug command
    usage: /<command> <args>
    aliases:
      - d